name: Build and Push to GHCR
on:
    push:
        branches:
            - main
        tags:
            - v*
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: brunsviga13rk/sfm
jobs:
    build:
        runs-on: ubuntu-latest
        if: >
            (! contains(github.event.head_commit.message, 'Skip-Container-Build')) &&
            (startsWith(github.ref, 'refs/tags/'))
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: "recursive"
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
    recon:
        runs-on: ubuntu-latest
        if: ${{ (!cancelled()) && contains(github.event.head_commit.message, 'Run-Reconstruct') }}
        needs: build
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: false
            - name: Extract Version
              id: infer_version
              env:
                  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
              run: |
                  export VERSION=$(echo "${COMMIT_MESSAGE}" | grep -Po '(?<=Run-Reconstruct: )v\d+\.\d+\.\d+')
                  echo "Running release action on version $VERSION"
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
            - name: Pull Docker Image
              run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.infer_version.outputs.version }}
            - name: Pull Dataset
              run: make pull
            - name: Reconnstruct Brunsviga 13 RK
              run: |
                  sed -i "/IMAGE_TAG/c\IMAGE_TAG=\"${{ steps.infer_version.outputs.version }}\"" .env
                  make run
            - name: Prepare Release
              run: |
                  cp output/reconstruction_sequential/scene.ply Model.ply
                  touch Release.txt
                  echo "tag: ${{ github.ref_name }}" >> Release.txt
                  echo "sha: ${{ github.sha }}" >> Release.txt
            - name: Release 3D Model
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      dataset.tar.gz
                      Model.ply
                      Release.txt
